#!/usr/bin/env python3
"""
Generate OpenROAD TCL script to place macros.

This creates a simple TCL script that can be sourced in OpenROAD
to set macro positions from our placement algorithm.

Usage:
    python scripts/generate_macro_placement_tcl.py --benchmark ariane133
"""

import re
import sys
import argparse
import torch
from pathlib import Path

from macro_place.loader import load_benchmark_from_dir


def generate_random_placement(benchmark, seed=42):
    """Generate random placement for demo."""
    torch.manual_seed(seed)
    placement = torch.zeros(benchmark.num_macros, 2)

    for i in range(benchmark.num_macros):
        w, h = benchmark.macro_sizes[i]
        x_min, x_max = w / 2, benchmark.canvas_width - w / 2
        y_min, y_max = h / 2, benchmark.canvas_height - h / 2

        x = torch.rand(1) * (x_max - x_min) + x_min
        y = torch.rand(1) * (y_max - y_min) + y_min

        placement[i, 0] = x
        placement[i, 1] = y

    # Respect fixed macros
    fixed_mask = benchmark.macro_fixed
    if fixed_mask.any():
        placement[fixed_mask] = benchmark.macro_positions[fixed_mask]

    return placement


def write_openroad_placement_tcl(placement, benchmark, plc, output_file):
    """
    Write OpenROAD TCL script to place macros using place_macro command.

    Args:
        placement: [num_macros, 2] tensor of (x, y) positions in microns
        benchmark: Benchmark object
        plc: PlacementCost object
        output_file: Output TCL file path
    """
    with open(output_file, 'w') as f:
        f.write("# OpenROAD Macro Placement Script\n")
        f.write("# Generated by partcl-macro-place-challenge\n")
        f.write("#\n")
        f.write("# Usage: source this file after initialize_floorplan in OpenROAD\n")
        f.write("#\n\n")

        f.write("puts \"Placing macros...\"\n\n")

        # Convert to numpy for easier access
        placement_np = placement.cpu().numpy()

        # Place each macro using place_macro command
        placed_count = 0
        for i, macro_idx in enumerate(benchmark.hard_macro_indices):
            node = plc.modules_w_pins[macro_idx]
            instance_name = node.get_name()

            # Escape brackets for OpenROAD (e.g., "block[0]" -> "block\\[0\\]")
            instance_name_escaped = instance_name.replace('[', '\\[').replace(']', '\\]')

            x, y = placement_np[i]

            # Get macro size
            w = node.get_width()
            h = node.get_height()

            # place_macro uses lower-left corner, not center
            # So convert from center to lower-left
            x_ll = x - w / 2
            y_ll = y - h / 2

            # Get orientation
            orientation = node.get_orientation() if node.get_orientation() else "R0"

            f.write(f"# Placing {instance_name}\n")
            f.write(f"place_macro \\\n")
            f.write(f"    -macro_name {{{instance_name_escaped}}} \\\n")
            f.write(f"    -location {{{x_ll:.6f} {y_ll:.6f}}} \\\n")
            f.write(f"    -orientation {orientation}\n\n")

            placed_count += 1

        f.write(f"puts \"Placed {placed_count} macros\"\n")

    print(f"✓ Generated OpenROAD placement TCL: {output_file}")
    print(f"  Placed {placed_count} macros")


def _plc_extract_group_and_index(plc_name):
    """Extract sram group prefix and flat macro index from a .plc name.

    .plc format: i_cache_subsystem/i_icache/sram_block[0].data_sram/macro_mem[K].i_ram
    Returns: (group_prefix_in_odb_format, K)

    The group prefix is everything before 'macro_mem[K]', converted to ODB naming
    (brackets to underscores, '/' to '.').  K is the flat macro index within that group.
    """
    # Extract macro_mem index
    m = re.search(r'/macro_mem\[(\d+)\]\.i_ram$', plc_name)
    if not m:
        return None, None
    macro_idx = int(m.group(1))
    prefix = plc_name[:m.start()]

    # Convert prefix to ODB format: brackets -> underscores, '/' -> '.'
    prefix = re.sub(r'\[(\d+)\]\.', r'_\1__', prefix)
    prefix = re.sub(r'\[(\d+)\]$', r'_\1__', prefix)
    prefix = prefix.replace('/', '.')

    return prefix, macro_idx


def _plc_direct_odb_name(plc_name):
    """Convert direct .plc macro names to synthesized ODB instance names."""
    name = re.sub(r'\[(\d+)\]\.', r'_\1__', plc_name)
    name = re.sub(r'\[(\d+)\]$', r'_\1__', name)
    name = name.replace('/', '.')
    name = name.replace('.sram_instance', '_sram_instance')
    name = name.replace('.fr_sp_instance', '_fr_sp_instance')
    return name


# LEF/DEF orientation strings (N/S/E/W + flipped variants) → ODB enum strings
# (R0/R90/R180/R270 + mirror variants). `dbInst setLocationOrient` rejects
# LEF/DEF names with "ValueError Unknown orientation". Place-macro accepted
# both forms; the direct dbInst API does not.
_ORIENT_LEF_TO_ODB = {
    "N": "R0", "R0": "R0",
    "W": "R90", "R90": "R90",
    "S": "R180", "R180": "R180",
    "E": "R270", "R270": "R270",
    "FN": "MY", "MY": "MY",
    "FW": "MXR90", "MXR90": "MXR90",
    "FS": "MX", "MX": "MX",
    "FE": "MYR90", "MYR90": "MYR90",
}


def _to_odb_orient(orient: str) -> str:
    """Map any LEF/DEF or ODB orient string to the ODB enum form."""
    return _ORIENT_LEF_TO_ODB.get(orient, "R0")


def _plc_to_odb_name_brackets(plc_name):
    r"""Convert .plc hierarchical name to ODB name with yosys-escaped brackets.

    Different yosys runs produce different ODB naming. Ariane133 converts
    brackets to `_N__` underscores. Ariane136 keeps brackets but with
    YOSYS's literal-backslash escape: e.g. `sram_block\[0\]` (verified by
    dumping ODB via openroad on 2026-05-15). To make Tcl `findInst` match,
    we must emit the exact ODB name including the backslashes.
    """
    name = plc_name.replace('/', '.')
    return name.replace('[', r'\[').replace(']', r'\]')


def _repair_direct_macro_overlaps(direct_data, padding=2.0, max_iters=100, min_spacing=0.0):
    """Repair direct macro lower-left boxes before emitting ORFS TCL.

    With ``min_spacing > 0``, also pushes apart non-overlapping pairs whose
    axis-aligned gap is below the threshold on BOTH axes (i.e. close enough
    that PDN can't fit a power strap through the channel). Required for
    nvdla (PDN-0179 channel-repair failures) and matches the Tier 2
    evaluator's auto-push of ≥12 μm clearance.
    """
    repaired = [list(item) for item in direct_data]
    for _ in range(max_iters):
        changed = False
        for i in range(len(repaired)):
            for j in range(i + 1, len(repaired)):
                _, xi, yi, wi, hi, _, _ = repaired[i]
                _, xj, yj, wj, hj, _, _ = repaired[j]
                overlap_x = min(xi + wi, xj + wj) - max(xi, xj)
                overlap_y = min(yi + hi, yj + hj) - max(yi, yj)

                if overlap_x > 0.0 and overlap_y > 0.0:
                    # True 2D overlap: push apart on the cheaper axis.
                    if overlap_x <= overlap_y:
                        delta = overlap_x + padding
                        sign = 1.0 if xj >= xi else -1.0
                        repaired[i][1] -= sign * delta * 0.5
                        repaired[j][1] += sign * delta * 0.5
                    else:
                        delta = overlap_y + padding
                        sign = 1.0 if yj >= yi else -1.0
                        repaired[i][2] -= sign * delta * 0.5
                        repaired[j][2] += sign * delta * 0.5
                    changed = True
                elif min_spacing > 0.0:
                    # Non-overlapping in 2D, but maybe too close on the
                    # narrowest axis to route a PDN strap. Treat axis-aligned
                    # overlap (overlap_*>0) as a 0-width gap on that axis.
                    gap_x = max(0.0, -overlap_x)
                    gap_y = max(0.0, -overlap_y)
                    # If either axis already has enough clearance, PDN can fit.
                    if gap_x >= min_spacing or gap_y >= min_spacing:
                        continue
                    # Push apart on whichever axis has the smaller gap (cheaper
                    # to bring up to threshold).
                    if gap_x <= gap_y:
                        delta = (min_spacing - gap_x) + padding
                        sign = 1.0 if xj >= xi else -1.0
                        repaired[i][1] -= sign * delta * 0.5
                        repaired[j][1] += sign * delta * 0.5
                    else:
                        delta = (min_spacing - gap_y) + padding
                        sign = 1.0 if yj >= yi else -1.0
                        repaired[i][2] -= sign * delta * 0.5
                        repaired[j][2] += sign * delta * 0.5
                    changed = True
        if not changed:
            break
    return repaired


def _clamp_direct_macros_to_core(direct_data, core_area):
    """Bring macro lower-lefts inside the core box via per-macro clip.

    Per-macro clip is the right tool here: when only a few macros are
    out-of-bounds, only those get moved (no cascading bunching). The
    earlier "uniform translate" attempt moved ALL macros, which pushed
    macros near the UR boundary off-canvas → massive UR bunching (66
    macros at the same x for ariane136). Bunching at LL only happens
    for the few macros that were OOB anyway; if their other-axis
    coordinates differ they don't actually overlap.
    """
    if core_area is None:
        return direct_data
    core_x_min, core_y_min, core_x_max, core_y_max = core_area
    clamped = []
    for odb_name, x_ll, y_ll, width, height, orient, plc_name in direct_data:
        x_ll = max(core_x_min, min(x_ll, core_x_max - width))
        y_ll = max(core_y_min, min(y_ll, core_y_max - height))
        clamped.append((odb_name, x_ll, y_ll, width, height, orient, plc_name))
    return clamped


def _has_direct_macro_overlaps(direct_data):
    for i in range(len(direct_data)):
        _, xi, yi, wi, hi, _, _ = direct_data[i]
        for j in range(i + 1, len(direct_data)):
            _, xj, yj, wj, hj, _, _ = direct_data[j]
            overlap_x = min(xi + wi, xj + wj) - max(xi, xj)
            overlap_y = min(yi + hi, yj + hj) - max(yi, yj)
            if overlap_x > 0.0 and overlap_y > 0.0:
                return True
    return False


def _legalize_direct_macros_to_core(direct_data, core_area, max_rounds=20, min_spacing=0.0):
    legalized = _clamp_direct_macros_to_core(direct_data, core_area)
    for _ in range(max_rounds):
        repaired = _repair_direct_macro_overlaps(legalized, min_spacing=min_spacing)
        clamped = _clamp_direct_macros_to_core(repaired, core_area)
        if clamped == legalized or not _has_direct_macro_overlaps(clamped):
            return clamped
        legalized = clamped
    return legalized


def _orfs_direct_macro_size(plc_name, width, height):
    """Use ORFS LEF sizes for direct mempool fakeram macros when known."""
    if "genblk1.sram_instance" in plc_name:
        return 78.660, 64.400
    if "genblk1.fr_sp_instance" in plc_name:
        return 77.900, 62.200
    return width, height


def write_orfs_macro_placement(placement, benchmark, plc, output_file, core_area=None):
    """
    Write macro placement in ORFS format using place_macro command.

    Uses a two-pass TCL matching strategy to handle the naming differences
    between .plc protobuf names and ODB/synthesized names:
    - .plc uses flat indexing: macro_mem[K].i_ram (K=0..N-1)
    - ODB uses generate blocks: genblk1_G__i_ram.macro_mem_M

    The mapping K -> (G,M) depends on the SRAM wrapper type (4, 3, or 1 mems
    per genblk). Instead of guessing, we match at runtime by grouping ODB
    instances by their sram block prefix and assigning linear indices.

    Args:
        placement: [num_macros, 2] tensor of (x, y) positions in microns
        benchmark: Benchmark object
        plc: PlacementCost object
        output_file: Output TCL file path
        core_area: Optional tuple (x_min, y_min, x_max, y_max) to clamp positions
    """
    from collections import defaultdict

    placement_np = placement.cpu().numpy()

    # Build placement data keyed by (group_prefix, flat_macro_index)
    group_data = defaultdict(dict)  # group_prefix -> {K: (x, y, orient, plc_name)}
    direct_data = []  # (odb_name, x, y, orient, plc_name)
    total_macros = 0

    for i, macro_idx in enumerate(benchmark.hard_macro_indices):
        node = plc.modules_w_pins[macro_idx]
        plc_name = node.get_name()
        x, y = placement_np[i]
        w = node.get_width()
        h = node.get_height()
        x_ll = x - w / 2
        y_ll = y - h / 2

        if core_area is not None:
            margin = 2.0
            core_x_min, core_y_min, core_x_max, core_y_max = core_area
            x_ll = max(core_x_min + margin, min(x_ll, core_x_max - w - margin))
            y_ll = max(core_y_min + margin, min(y_ll, core_y_max - h - margin))

        orientation = _to_odb_orient(node.get_orientation() if node.get_orientation() else "R0")
        group_prefix, macro_k = _plc_extract_group_and_index(plc_name)

        if group_prefix is not None:
            group_data[group_prefix][macro_k] = (x_ll, y_ll, orientation, plc_name)
            # Also emit a bracket-preserving direct entry: ariane133-style synth
            # uses underscores (matched by group-pass), but ariane136-style keeps
            # brackets literally so the group-pass regex misses them. Direct Pass 0
            # tries the exact ODB name; findInst returns NULL for the wrong form
            # and falls through, so we never double-place.
            bracket_odb_name = _plc_to_odb_name_brackets(plc_name)
            direct_data.append(
                (
                    bracket_odb_name,
                    x_ll,
                    y_ll,
                    w,
                    h,
                    orientation,
                    plc_name,
                )
            )
            total_macros += 1
        else:
            repair_w, repair_h = _orfs_direct_macro_size(plc_name, w, h)
            direct_data.append(
                (
                    _plc_direct_odb_name(plc_name),
                    x_ll,
                    y_ll,
                    repair_w,
                    repair_h,
                    orientation,
                    plc_name,
                )
            )
            total_macros += 1
    # min_spacing=12.0 μm: enforces enough channel width between any pair of
    # macros for PDN to route metal1 power straps. Matches the Tier 2 evaluator's
    # ≥12 μm auto-push. Required by nvdla (PDN-0179 channel-repair failures).
    # No-op for previously-passing designs where macros are already >12 μm apart.
    direct_data = _legalize_direct_macros_to_core(direct_data, core_area, min_spacing=12.0)

    with open(output_file, 'w') as f:
        f.write("# Macro Placement for OpenROAD-flow-scripts\n")
        f.write("# Generated by partcl-macro-place-challenge\n")
        f.write("#\n")
        f.write("# Two-pass runtime matching: groups ODB macros by sram block prefix,\n")
        f.write("# then matches to .plc macro_mem[K] by linear index within each group.\n\n")

        # Emit placement data: dict of group_prefix -> dict of flat_index -> {x y orient}
        f.write("# Placement data: group_prefix -> flat_index -> {x y orient plc_name}\n")
        f.write("set _gpd [dict create]\n")
        for group_prefix in sorted(group_data.keys()):
            for k in sorted(group_data[group_prefix].keys()):
                x_ll, y_ll, orient, plc_name = group_data[group_prefix][k]
                # Tcl curly braces ({}) prevent command substitution; required
                # because plc_name contains brackets like sram_block[0] which
                # Tcl would otherwise try to evaluate as `[0]` command.
                f.write(f'dict set _gpd {{{group_prefix}}} {k} [list {x_ll:.6f} {y_ll:.6f} {orient} {{{plc_name}}}]\n')
        f.write("\n")
        f.write("# Direct placement data: exact ODB instance name -> {x y orient plc_name}\n")
        f.write("set _direct [dict create]\n")
        for odb_name, x_ll, y_ll, _w, _h, orient, plc_name in direct_data:
            f.write(
                # Use Tcl curly braces ({}) for the key + plc_name so brackets
                # like sram_block[0] aren't treated as Tcl command substitution.
                f'dict set _direct {{{odb_name}}} [list {x_ll:.6f} {y_ll:.6f} {orient} {{{plc_name}}}]\n'
            )
        f.write("\n")

        # TCL matching logic
        f.write("""set block [ord::get_db_block]

# Pass 0: Place direct exact-name macro matches via dbInst API.
# We bypass `place_macro` because it mangles backslash-escaped names
# (yosys emits sram_block\[0\] in ODB; `place_macro -macro_name` can't
# round-trip those, but the dbInst handle from findInst is reliable).
set _placed 0
set _unmatched_direct [list]
set _dbu_per_micron [[ord::get_db_block] getDbUnitsPerMicron]
dict for {odb_name placement_data} $_direct {
    set inst [$block findInst $odb_name]
    if {$inst != "NULL"} {
        lassign $placement_data x y orient plc_name
        set x_dbu [expr {int($x * $_dbu_per_micron)}]
        set y_dbu [expr {int($y * $_dbu_per_micron)}]
        $inst setLocation $x_dbu $y_dbu
        $inst setLocationOrient $orient
        $inst setPlacementStatus FIRM
        incr _placed
    } else {
        lappend _unmatched_direct "$odb_name"
    }
}

# Pass 1: Collect all block instances, grouped by sram prefix
# ODB name pattern: PREFIX.genblk1_G__i_ram.macro_mem_M
# We extract PREFIX (everything before .genblk1_), G, and M.
set _odb_groups [dict create]
foreach inst [$block getInsts] {
    if {[$inst isBlock]} {
        set name [$inst getName]
        # Match the genblk pattern
        if {[regexp {^(.+)\\.genblk1_(\\d+)__i_ram\\.macro_mem_(\\d+)$} $name -> prefix genblk_idx mem_idx]} {
            dict lappend _odb_groups $prefix [list $genblk_idx $mem_idx $name]
        }
    }
}

# Pass 2: For each group, sort by (genblk_idx, mem_idx) to get linear ordering,
# then match to our .plc flat indices.
set _unmatched_odb [list]
set _unmatched_plc [list]

dict for {prefix entries} $_odb_groups {
    # Sort entries by genblk_idx then mem_idx (both numeric)
    set sorted_entries [lsort -command {apply {{a b} {
        lassign $a ga ma
        lassign $b gb mb
        set ga [expr {int($ga)}]; set ma [expr {int($ma)}]
        set gb [expr {int($gb)}]; set mb [expr {int($mb)}]
        if {$ga != $gb} { return [expr {$ga - $gb}] }
        return [expr {$ma - $mb}]
    }}} $entries]

    # Assign linear index K=0,1,2,...
    set k 0
    foreach entry $sorted_entries {
        lassign $entry genblk_idx mem_idx odb_name
        if {[dict exists $_gpd $prefix] && [dict exists [dict get $_gpd $prefix] $k]} {
            lassign [dict get [dict get $_gpd $prefix] $k] x y orient plc_name
            set inst2 [$block findInst $odb_name]
            if {$inst2 != "NULL"} {
                set x_dbu [expr {int($x * $_dbu_per_micron)}]
                set y_dbu [expr {int($y * $_dbu_per_micron)}]
                $inst2 setLocation $x_dbu $y_dbu
                $inst2 setLocationOrient $orient
                $inst2 setPlacementStatus FIRM
                incr _placed
            }
        } else {
            lappend _unmatched_odb "$odb_name (group=$prefix, k=$k)"
        }
        incr k
    }
}

""")
        f.write(f'puts "Placed $_placed macros (expected {total_macros})"\n')
        f.write(f'if {{$_placed != {total_macros}}} {{\n')
        f.write(f'    puts "WARNING: Expected {total_macros} macros but placed $_placed"\n')
        f.write('    if {[llength $_unmatched_direct] > 0} {\n')
        f.write('        puts "Unmatched direct instances:"\n')
        f.write('        foreach u $_unmatched_direct { puts "  $u" }\n')
        f.write('    }\n')
        f.write('    if {[llength $_unmatched_odb] > 0} {\n')
        f.write('        puts "Unmatched ODB instances:"\n')
        f.write('        foreach u $_unmatched_odb { puts "  $u" }\n')
        f.write('    }\n')
        f.write("}\n")

    print(f"✓ Generated ORFS macro placement TCL: {output_file}")
    print(
        f"  {total_macros} macros across {len(group_data)} sram groups "
        f"and {len(direct_data)} direct macros"
    )


def main():
    parser = argparse.ArgumentParser(description='Generate OpenROAD macro placement TCL')
    parser.add_argument('--benchmark', default='ariane133',
                       help='Benchmark to use (default: ariane133)')
    parser.add_argument('--output', default='output/place_macros.tcl',
                       help='Output TCL file (default: output/place_macros.tcl)')
    parser.add_argument('--seed', type=int, default=42,
                       help='Random seed (default: 42)')

    args = parser.parse_args()

    # Create output directory
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    print("=" * 80)
    print("Generate OpenROAD Macro Placement TCL")
    print("=" * 80)
    print()

    # Load benchmark
    print(f"Loading benchmark: {args.benchmark}...")
    flows_dir = Path("external/MacroPlacement/Flows/NanGate45")
    benchmark_path = flows_dir / args.benchmark / "netlist" / "output_CT_Grouping"

    if not benchmark_path.exists():
        testcases_dir = Path("external/MacroPlacement/Testcases/ICCAD04")
        benchmark_path = testcases_dir / args.benchmark
        if not benchmark_path.exists():
            print(f"ERROR: Benchmark not found: {args.benchmark}")
            return 1

    benchmark, plc = load_benchmark_from_dir(str(benchmark_path))
    print(f"  ✓ Loaded {benchmark.name} ({benchmark.num_macros} macros)")
    print()

    # Generate placement (you would replace this with your algorithm)
    print(f"Generating random placement (seed={args.seed})...")
    placement = generate_random_placement(benchmark, seed=args.seed)
    print(f"  ✓ Generated placement")
    print()

    # Write TCL script
    print(f"Writing OpenROAD TCL script...")
    write_openroad_placement_tcl(placement, benchmark, plc, str(output_path))
    print()

    print("=" * 80)
    print("USAGE")
    print("=" * 80)
    print()
    print("In your OpenROAD flow, after loading LEF/netlist:")
    print()
    print(f"  source {args.output}")
    print()
    print("This will place all macros at the computed positions.")
    print("=" * 80)

    return 0


if __name__ == "__main__":
    sys.exit(main())
